In [43]:
#import the necessary packages
import pandas as pd
import numpy as np

pd.options.display.max_rows =500
pd.options.display.max_columns =500
np.set_printoptions(threshold=np.inf)#no trunkcated lists

In [44]:
#Import the 'AviationData.csv' file using a proper encoding
aviation_data = pd.read_csv('./AviationData.csv', index_col=0, header=0, encoding='latin-1')
aviation_data.head()

/Users/Erin/opt/anaconda3/envs/learn-env/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3145: DtypeWarning: Columns (6,7,28) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,Injury.Severity,Aircraft.damage,Aircraft.Category,Registration.Number,Make,Model,Amateur.Built,Number.of.Engines,Engine.Type,FAR.Description,Schedule,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
Event.Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,Fatal(2),Destroyed,NaN,NC6404,Stinson,108-3,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,Fatal(4),Destroyed,NaN,N5069P,Piper,PA24-180,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.9222,-81.8781,NaN,NaN,Fatal(3),Destroyed,NaN,N5142R,Cessna,172M,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,Fatal(2),Destroyed,NaN,N1168J,Rockwell,112,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,Fatal(1),Destroyed,NaN,N15NY,Cessna,501,No,NaN,NaN,NaN,NaN,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

In [45]:
aviation_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 88889 entries, 20001218X45444 to 20221230106513
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Investigation.Type      88889 non-null  object
 1   Accident.Number         88889 non-null  object
 2   Event.Date              88889 non-null  object
 3   Location                88837 non-null  object
 4   Country                 88663 non-null  object
 5   Latitude                34382 non-null  object
 6   Longitude               34373 non-null  object
 7   Airport.Code            50249 non-null  object
 8   Airport.Name            52790 non-null  object
 9   Injury.Severity         87889 non-null  object
 10  Aircraft.damage         85695 non-null  object
 11  Aircraft.Category       32287 non-null  object
 12  Registration.Number     87572 non-null  object
 13  Make                    88826 non-null  object
 14  Model                   88797 non-null  object
 15  Amateur.Built           88787 non-null  object
 16  Number.of.Engines       82805 non-null  float64
 17  Engine.Type             81812 non-null  object
 18  FAR.Description         32023 non-null  object
 19  Schedule                12582 non-null  object
 20  Purpose.of.flight       82697 non-null  object
 21  Air.carrier             16648 non-null  object
 22  Total.Fatal.Injuries    77488 non-null  float64
 23  Total.Serious.Injuries  76379 non-null  float64
 24  Total.Minor.Injuries    76956 non-null  float64
 25  Total.Uninjured         82977 non-null  float64
 26  Weather.Condition       84397 non-null  object
 27  Broad.phase.of.flight   61724 non-null  object
 28  Report.Status           82508 non-null  object
 29  Publication.Date        75118 non-null  object
dtypes: float64(5), object(25)
memory usage: 21.0+ MB

In [46]:
aviation_data.describe(include='all') #getting an overview/preview of the data

,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,Injury.Severity,Aircraft.damage,Aircraft.Category,Registration.Number,Make,Model,Amateur.Built,Number.of.Engines,Engine.Type,FAR.Description,Schedule,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
count,88889,88889,88889,88837,88663,34382,34373,50249,52790,87889,85695,32287,87572,88826,88797,88787,82805.000000,81812,32023,12582,82697,16648,77488.000000,76379.000000,76956.000000,82977.000000,84397,61724,82508,75118
unique,2,88863,14782,27758,219,25592,27156,10375,24871,109,4,15,79105,8237,12318,2,NaN,13,31,3,26,13590,NaN,NaN,NaN,NaN,4,12,17075,2924
top,Accident,WPR22LA201,2000-07-08,"ANCHORAGE, AK",United States,332739N,0112457W,NONE,Private,Non-Fatal,Substantial,Airplane,NONE,Cessna,152,No,NaN,Reciprocating,091,NSCH,Personal,Pilot,NaN,NaN,NaN,NaN,VMC,Landing,Probable Cause,25-09-2020
freq,85015,2,25,434,82248,19,24,1488,240,67357,64148,27617,344,22227,2367,80312,NaN,69530,18221,4474,49448,258,NaN,NaN,NaN,NaN,77303,15428,61754,17019
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.146585,NaN,NaN,NaN,NaN,NaN,0.647855,0.279881,0.357061,5.325440,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.446510,NaN,NaN,NaN,NaN,NaN,5.485960,1.544084,2.235625,27.913634,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,1.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,2.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.000000,NaN,NaN,NaN,NaN,NaN,349.000000,161.000000,380.000000,699.000000,NaN,NaN,NaN,NaN

In [47]:
#better to work with a copy then to mess up the original
aviation_data_clean = aviation_data.copy()

Dealing with missing values in the 'Model' and 'Make' columns requires thoughtful consideration, as these columns are crucial for identifying the aircraft involved in accidents.

In [48]:
#I need to start with cleaning up the Make and Model columns.
#I'm creating a dictionary to map Models to Makes

model_to_make = aviation_data_clean.dropna(subset=['Model', 'Make']).set_index('Model')['Make'].to_dict()

In [49]:
#Now I can write a function to fill missing 'Make' based on 'Model'
def fill_make(row):
    if pd.isnull(row['Make']) and not pd.isnull(row['Model']):
        return model_to_make.get(row['Model'])
    return row['Make']

In [50]:
#Finally, apply this function to fill missing 'Make' values
aviation_data_clean['Make']=aviation_data_clean.apply(fill_make, axis=1)

In [51]:
aviation_data_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 88889 entries, 20001218X45444 to 20221230106513
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Investigation.Type      88889 non-null  object
 1   Accident.Number         88889 non-null  object
 2   Event.Date              88889 non-null  object
 3   Location                88837 non-null  object
 4   Country                 88663 non-null  object
 5   Latitude                34382 non-null  object
 6   Longitude               34373 non-null  object
 7   Airport.Code            50249 non-null  object
 8   Airport.Name            52790 non-null  object
 9   Injury.Severity         87889 non-null  object
 10  Aircraft.damage         85695 non-null  object
 11  Aircraft.Category       32287 non-null  object
 12  Registration.Number     87572 non-null  object
 13  Make                    88839 non-null  object
 14  Model                   88797 non-null  object
 15  Amateur.Built           88787 non-null  object
 16  Number.of.Engines       82805 non-null  float64
 17  Engine.Type             81812 non-null  object
 18  FAR.Description         32023 non-null  object
 19  Schedule                12582 non-null  object
 20  Purpose.of.flight       82697 non-null  object
 21  Air.carrier             16648 non-null  object
 22  Total.Fatal.Injuries    77488 non-null  float64
 23  Total.Serious.Injuries  76379 non-null  float64
 24  Total.Minor.Injuries    76956 non-null  float64
 25  Total.Uninjured         82977 non-null  float64
 26  Weather.Condition       84397 non-null  object
 27  Broad.phase.of.flight   61724 non-null  object
 28  Report.Status           82508 non-null  object
 29  Publication.Date        75118 non-null  object
dtypes: float64(5), object(25)
memory usage: 21.0+ MB

In this code, I first created a dictionary model_to_make that maps 'Model' values to their corresponding 'Make' values using the non-missing rows in the 'Model' and 'Make' columns.

Then, I defined a function fill_make that takes a row as input. The function checks if the 'Make' value is missing and the 'Model' value is present. If both conditions are met, it uses the model_to_make dictionary to look up the corresponding 'Make' value for that 'Model'.

Finally, I applied the fill_make function to the entire DataFrame using the apply function along axis=1, which means applying the function row-wise.

By running this code, the missing 'Make' values in the DataFrame were filled based on the available 'Model' values in other rows. In this case the 'Model' is more specific and can be used to infer the 'Make' when the value is missing. I thought that this approach would be helpful to fill in some missing values in the 'Make' column and would produce additional values that will contribute to accurately representing this data set. By using this approach, 13 values were inferred and now those rows can be used in the final analysis.

In [52]:
#Next, I'll be dealing with duplicate values. 
#I'm going to identify and validate the duplicates in the 'Model' column
duplicates_model = aviation_data_clean['Model'].duplicated(keep=False)
duplicate_models = aviation_data_clean[duplicates_model]['Model'].unique()
aviation_data_clean['Model'].value_counts()

152                 2367
172                 1756
172N                1164
PA-28-140            932
150                  829
                    ...
ARROW SPORT            1
CHAMPION 7GCAA         1
AS-350B ECUREUIL       1
BN2-A                  1
Kitfox 6               1
Name: Model, Length: 12318, dtype: int64

In [53]:
#looks like we have both string and float data so combined
aviation_data_clean['Model'] = aviation_data_clean['Model'].apply(str)

In [54]:
#now make them uppercase
aviation_data_clean['Model'] = aviation_data_clean['Model'].map(str.upper)

In [55]:
aviation_data_clean['Model'].value_counts()

152              2367
172              1756
172N             1164
PA-28-140         932
150               829
                 ...
P60                 1
A-4                 1
SZD-48 JANTAR       1
CASA-212            1
SWIFT               1
Name: Model, Length: 11647, dtype: int64

In [56]:
#I'm going to identify and validate the duplicates in the 'Make' column
duplicates_make = aviation_data_clean['Make'].duplicated(keep=False)
duplicate_makes = aviation_data_clean[duplicates_make]['Make'].unique()
aviation_data_clean['Make'].value_counts()

Cessna       22227
Piper        12029
CESSNA        4922
Beech         4330
PIPER         2841
             ...
Sheats           1
Riekkenen        1
MIGAS            1
Steinbaum        1
Brewer           1
Name: Make, Length: 8237, dtype: int64

In [57]:
#looks like we have both string and float data so combined
aviation_data_clean['Make'] = aviation_data_clean['Make'].apply(str)

In [58]:
#now make them uppercase
aviation_data_clean['Make'] = aviation_data_clean['Make'].map(str.upper)

In [59]:
aviation_data_clean['Make'].value_counts()

CESSNA           27149
PIPER            14870
BEECH             5372
BOEING            2745
BELL              2723
                 ...
APCO                 1
MARLEY               1
HAROLD VANDER        1
FARLAND              1
GABLE                1
Name: Make, Length: 7589, dtype: int64

In [60]:
#Drop rows with missing values in either 'Make' or 'Model' columns
aviation_data_washed = aviation_data_clean.dropna(subset=["Make", 'Model'])
print(aviation_data_washed.info())

<class 'pandas.core.frame.DataFrame'>
Index: 88889 entries, 20001218X45444 to 20221230106513
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Investigation.Type      88889 non-null  object
 1   Accident.Number         88889 non-null  object
 2   Event.Date              88889 non-null  object
 3   Location                88837 non-null  object
 4   Country                 88663 non-null  object
 5   Latitude                34382 non-null  object
 6   Longitude               34373 non-null  object
 7   Airport.Code            50249 non-null  object
 8   Airport.Name            52790 non-null  object
 9   Injury.Severity         87889 non-null  object
 10  Aircraft.damage         85695 non-null  object
 11  Aircraft.Category       32287 non-null  object
 12  Registration.Number     87572 non-null  object
 13  Make                    88889 non-null  object
 14  Model                   88889 non-null  object
 15  Amateur.Built           88787 non-null  object
 16  Number.of.Engines       82805 non-null  float64
 17  Engine.Type             81812 non-null  object
 18  FAR.Description         32023 non-null  object
 19  Schedule                12582 non-null  object
 20  Purpose.of.flight       82697 non-null  object
 21  Air.carrier             16648 non-null  object
 22  Total.Fatal.Injuries    77488 non-null  float64
 23  Total.Serious.Injuries  76379 non-null  float64
 24  Total.Minor.Injuries    76956 non-null  float64
 25  Total.Uninjured         82977 non-null  float64
 26  Weather.Condition       84397 non-null  object
 27  Broad.phase.of.flight   61724 non-null  object
 28  Report.Status           82508 non-null  object
 29  Publication.Date        75118 non-null  object
dtypes: float64(5), object(25)
memory usage: 21.0+ MB
None

I had to use the dropna() function with the subset parameter set to ['Make', 'Model'], which specifies that I want to drop rows where either the 'Make' or 'Model' column have missing values.

The resulting DataFrame aviation_data_washed will contain only the rows with both 'Make' and 'Model' values. The info() method shows me information about the non-null values in each column to verify that there are no missing values in the 'Make' and 'Model' columns.

After this step, I will work with the cleaned DataFrame aviation_data_washed, which contains only the rows that have both 'Make' and 'Model' values, without any missing values in those columns.

In [61]:
aviation_data_washed.head()

,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,Injury.Severity,Aircraft.damage,Aircraft.Category,Registration.Number,Make,Model,Amateur.Built,Number.of.Engines,Engine.Type,FAR.Description,Schedule,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
Event.Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,Fatal(2),Destroyed,NaN,NC6404,STINSON,108-3,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,Fatal(4),Destroyed,NaN,N5069P,PIPER,PA24-180,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.9222,-81.8781,NaN,NaN,Fatal(3),Destroyed,NaN,N5142R,CESSNA,172M,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,Fatal(2),Destroyed,NaN,N1168J,ROCKWELL,112,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,Fatal(1),Destroyed,NaN,N15NY,CESSNA,501,No,NaN,NaN,NaN,NaN,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

In [62]:
#Now, I'm organizing and cleaning the Injury.Serverity column

#In this code, I'm using the assign() method to create a new DataFrame
#that includes the original 'Injury.Severity' column as well as 
#a new column named 'InjurySeverity_Duplicated', which contains 
#the same values as the 'Injury.Severity' column.

aviation_data_washed['Injury.Severity_copy'] = aviation_data_washed.loc[:,'Injury.Severity']

#verify that the column was successfully created
aviation_data_washed.head()

,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,Injury.Severity,Aircraft.damage,Aircraft.Category,Registration.Number,Make,Model,Amateur.Built,Number.of.Engines,Engine.Type,FAR.Description,Schedule,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date,Injury.Severity_copy
Event.Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,Fatal(2),Destroyed,NaN,NC6404,STINSON,108-3,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN,Fatal(2)
20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,Fatal(4),Destroyed,NaN,N5069P,PIPER,PA24-180,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996,Fatal(4)
20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.9222,-81.8781,NaN,NaN,Fatal(3),Destroyed,NaN,N5142R,CESSNA,172M,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007,Fatal(3)
20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,Fatal(2),Destroyed,NaN,N1168J,ROCKWELL,112,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000,Fatal(2)
20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,Fatal(1),Destroyed,NaN,N15NY,CESSNA,501,No,NaN,NaN,NaN,NaN,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980,Fatal(1)

In [63]:
#use .loc to change the vlaue of 'Injury.Severity_copy' based on 'Total.Fatal.Injuries' column
aviation_data_washed.loc[aviation_data_washed['Total.Fatal.Injuries'] >=1, 'Injury.Severity_copy']= "FATAL"

In [64]:
#Locate all of the unique values in the 'Injury.Severity_copy' column
unique_severity_values = aviation_data_washed['Injury.Severity_copy'].unique()

#View the unique values
print(unique_severity_values)

['FATAL' 'Non-Fatal' 'Incident' 'Unavailable' 'Fatal' nan 'Minor'
 'Serious']

Here I use the .loc method with the condition df['Total.Fatal.Injuries'] >= 1 to selectively change the values in the 'Injury.Severity_copy' column. If the value in the 'Total.Fatal.Injuries' column is 1 or more, the corresponding 'Injury.Severity_copy' value is changed to 'FATAL' for those rows. Otherwise, the 'Injury.Severity_copy' value remains unchanged.

After running this code, the 'Injury.Severity_copy' column will have 'FATAL' for rows where 'Total.Fatal.Injuries' is 1 or more, and for other rows, it will retain its original 'Injury.Severity' values.

In [65]:
#verify the changes
aviation_data_washed.head()

,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,Injury.Severity,Aircraft.damage,Aircraft.Category,Registration.Number,Make,Model,Amateur.Built,Number.of.Engines,Engine.Type,FAR.Description,Schedule,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date,Injury.Severity_copy
Event.Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,Fatal(2),Destroyed,NaN,NC6404,STINSON,108-3,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN,FATAL
20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,Fatal(4),Destroyed,NaN,N5069P,PIPER,PA24-180,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996,FATAL
20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.9222,-81.8781,NaN,NaN,Fatal(3),Destroyed,NaN,N5142R,CESSNA,172M,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007,FATAL
20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,Fatal(2),Destroyed,NaN,N1168J,ROCKWELL,112,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000,FATAL
20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,Fatal(1),Destroyed,NaN,N15NY,CESSNA,501,No,NaN,NaN,NaN,NaN,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980,FATAL

In [66]:
#I'm going to check these unique values for any corresponding values in other columns that could help me fill in the missing/incorrect data

#list the values to search for in the 'Injury.Severity_copy' column
severity_values = ['Incident', 'Unavailable', 'Fatal', 'Minor', 'nan', 'Serious']

#search for rows with 'Injury.Severity_copy' values in the list and access corresponding 'Total.Fatal.Injuries'
corresponding_fatal_injuries = aviation_data_washed.loc[aviation_data_washed['Injury.Severity_copy'].isin(severity_values), ['Injury.Severity_copy','Total.Fatal.Injuries']]

#verify that it worked
corresponding_fatal_injuries

#I used the .loc method with a condition to filter the rows with 'Injury.Severity_copy' values matching any of the specified severity values.

#To access both the 'Injury.Severity_copy' column and its corresponding 'Total.Fatal.Injuries' column, I passed a list ['Injury.Severity_copy', 'Total.Fatal.Injuries'] to the .loc method.

#The variable corresponding_fatal_injuries is a DataFrame containing both the 'Injury.Severity_copy' and 'Total.Fatal.Injuries' columns for rows where 'Injury.Severity_copy' matches any of the specified severity values.

#When I printed corresponding_fatal_injuries, I now see the 'Injury.Severity_copy' values along with their corresponding 'Total.Fatal.Injuries' values side by side.

               Injury.Severity_copy  Total.Fatal.Injuries
Event.Id
20020917X02333             Incident                   0.0
20020917X01764             Incident                   0.0
20020917X01897             Incident                   0.0
20020917X01765             Incident                   0.0
20020917X01766             Incident                   0.0
...                             ...                   ...
20221227106496                Minor                   0.0
20221221106483                Minor                   0.0
20221222106486                Minor                   0.0
20221227106491                Minor                   0.0
20221230106513                Minor                   0.0

[2719 rows x 2 columns]

In [67]:
#it looks like the data is there and valid on my verification so I'll go ahead and change those values to 'Non-Fatal'
aviation_data_washed.loc[aviation_data_washed['Total.Fatal.Injuries'] ==0, 'Injury.Severity_copy'] = 'Non-Fatal'

unique_severity_values = aviation_data_washed['Injury.Severity_copy'].unique()

#View the unique values
print(unique_severity_values)

['FATAL' 'Non-Fatal' 'Incident' 'Unavailable']

> An **accident** is defined as “an occurrence associated with the
> operation of an aircraft which takes place between the time any person
> boards the aircraft with the intention of flight and all such persons
> have disembarked, and in which any person suffers death or serious
> injury, or in which the aircraft receives substantial damage”. An
> **incident** is defined as “an occurrence other than an accident,
> associated with the operation of an aircraft, which affects or could
> affect the safety of operations.”

In [68]:
#there are still missing values, however, based on the definition above, we can drop the rows labeled incident because only accidents contain fatalities.
#list the values to search for in the 'Injury.Severity_copy' column
severity_values = ['Unavailable']

#search for rows with 'Injury.Severity_copy' values in the list and access corresponding 'Total.Fatal.Injuries'
corresponding_fatal_injuries = aviation_data_washed.loc[aviation_data_washed['Injury.Severity_copy'].isin(severity_values), ['Injury.Severity_copy','Total.Fatal.Injuries', 'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured']]

#view this data
corresponding_fatal_injuries

,Injury.Severity_copy,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured
Event.Id,,,,,
20001213X32755,Unavailable,NaN,NaN,NaN,NaN
20001213X25766,Unavailable,NaN,NaN,NaN,NaN
20001213X27314,Unavailable,NaN,NaN,NaN,NaN
20001213X28159,Unavailable,NaN,NaN,NaN,NaN
20001212X22780,Unavailable,NaN,NaN,NaN,NaN
20001212X23228,Unavailable,NaN,NaN,NaN,NaN
20001212X16360,Unavailable,NaN,NaN,NaN,NaN
20001212X16672,Unavailable,NaN,NaN,NaN,NaN
20001212X16717,Unavailable,NaN,NaN,NaN,NaN
20001212X17332,Unavailable,NaN,NaN,NaN,NaN
20001212X17352,Unavailable,NaN,NaN,NaN,NaN
20001212X18218,Unavailable,NaN,NaN,NaN,NaN
20001212X18231,Unavailable,NaN,NaN,NaN,NaN
20001212X18402,Unavailable,NaN,NaN,NaN,NaN
20001212X18502,Unavailable,NaN,NaN,NaN,NaN
20001212X18579,Unavailable,NaN,NaN,NaN,NaN
20001212X18646,Unavailable,NaN,NaN,NaN,NaN
20001211X14075,Unavailable,NaN,NaN,NaN,NaN
20001211X14203,Unavailable,NaN,NaN,NaN,NaN
20001211X14205,Unavailable,NaN,NaN,NaN,NaN
20001211X14228,Unavailable,NaN,NaN,NaN,NaN
20001206X02569,Unavailable,NaN,NaN,NaN,NaN
20001208X07151,Unavailable,NaN,NaN,NaN,NaN
20010711X01373,Unavailable,NaN,NaN,NaN,NaN
20010711X01374,Unavailable,NaN,NaN,NaN,NaN
20001208X07697,Unavailable,NaN,NaN,NaN,NaN
20001208X08352,Unavailable,NaN,NaN,NaN,NaN
20001208X08992,Unavailable,NaN,NaN,NaN,NaN
20001208X08991,Unavailable,NaN,NaN,NaN,NaN
20001208X09238,Unavailable,NaN,NaN,NaN,NaN
20001208X09295,Unavailable,NaN,NaN,NaN,NaN
20010711X01369,Unavailable,NaN,NaN,NaN,NaN
20001211X09838,Unavailable,NaN,NaN,NaN,NaN
20001211X09839,Unavailable,NaN,NaN,NaN,NaN
20001211X10045,Unavailable,NaN,NaN,NaN,NaN
20001211X10826,Unavailable,NaN,NaN,NaN,NaN
20001211X11405,Unavailable,NaN,NaN,NaN,NaN
20001211X11538,Unavailable,NaN,NaN,NaN,NaN
20001204X00045,Unavailable,NaN,NaN,NaN,NaN
20001205X00299,Unavailable,NaN,NaN,NaN,NaN
20001205X00297,Unavailable,NaN,NaN,NaN,NaN
20001205X00483,Unavailable,NaN,NaN,NaN,NaN
20010330X00670,Unavailable,NaN,NaN,NaN,NaN
20001212X19734,Unavailable,NaN,NaN,NaN,NaN
20001212X20608,Unavailable,NaN,NaN,NaN,NaN
20010105X00025,Unavailable,NaN,NaN,NaN,NaN
20010329X00665,Unavailable,NaN,NaN,NaN,NaN
20020104X00030,Unavailable,NaN,NaN,NaN,NaN
20010904X01864,Unavailable,NaN,NaN,NaN,NaN
20020104X00027,Unavailable,NaN,NaN,NaN,NaN
20011128X02308,Unavailable,NaN,NaN,NaN,NaN
20020226X00261,Unavailable,NaN,NaN,NaN,NaN
20020322X00386,Unavailable,NaN,NaN,NaN,NaN
20020719X01171,Unavailable,NaN,NaN,NaN,NaN
20031008X01681,Unavailable,NaN,NaN,NaN,NaN
20040528X00699,Unavailable,NaN,NaN,NaN,NaN
20040528X00698,Unavailable,NaN,NaN,NaN,NaN
20071218X01948,Unavailable,NaN,NaN,NaN,NaN
20040202X00143,Unavailable,NaN,NaN,NaN,NaN
20040202X00145,Unavailable,NaN,NaN,NaN,NaN
20040202X00147,Unavailable,NaN,NaN,NaN,NaN
20080421X00521,Unavailable,NaN,NaN,NaN,NaN
20040817X01235,Unavailable,NaN,NaN,NaN,NaN
20040722X01041,Unavailable,NaN,NaN,NaN,NaN
20040812X01208,Unavailable,NaN,NaN,NaN,NaN
20041018X01645,Unavailable,NaN,NaN,NaN,NaN
20041209X01954,Unavailable,NaN,NaN,NaN,NaN
20050926X01529,Unavailable,NaN,NaN,NaN,NaN
20050915X01467,Unavailable,NaN,NaN,NaN,0.0
20050617X00805,Unavailable,NaN,NaN,NaN,NaN
20050628X00886,Unavailable,NaN,NaN,NaN,NaN
20050817X01260,Unavailable,NaN,NaN,NaN,NaN
20051109X01810,Unavailable,NaN,NaN,NaN,NaN
20060208X00178,Unavailable,NaN,NaN,NaN,NaN
20081003X63354,Unavailable,NaN,NaN,NaN,NaN
20070814X01180,Unavailable,NaN,NaN,NaN,NaN
20060705X00864,Unavailable,NaN,NaN,NaN,NaN
20060801X01067,Unavailable,NaN,NaN,NaN,NaN
20060918X01362,Unavailable,NaN,NaN,NaN,NaN
20061020X01543,Unavailable,NaN,NaN,NaN,NaN
20061122X01703,Unavailable,NaN,NaN,NaN,NaN
20070531X00673,Unavailable,NaN,NaN,NaN,NaN
20071108X01758,Unavailable,NaN,NaN,NaN,NaN
20070905X01309,Unavailable,NaN,NaN,NaN,NaN
20071001X01488,Unavailable,NaN,NaN,NaN,NaN

I'm going to leave these 'Unavailable' values in my analysis because if they happen to all coresspond to a particular make a model, that could be a red-flag. 

I will drop the 'incident rows from my analysis however because those rows, by definition, don't indicate fatalities.

In [37]:
#list the values in 'Injury.Severity_copy' that I'll be correlating to 'Make' and 'Model'
severity_values_to_find = ['FATAL', 'Unavailable']

#filter the rows with 'Injury.Severity_copy' values in the list and coresspond them to 'Make' and 'Model'
fatality_correspond_make_model = aviation_data_washed.loc[aviation_data_washed["Injury.Severity_copy"].isin(severity_values_to_find), ['Injury.Severity_copy', 'Make', 'Model']]

print(fatality_correspond_make_model.value_counts())

Injury.Severity_copy  Make                      Model
FATAL                 CESSNA                    152                  250
                                                172                  211
                                                172N                 203
                      PIPER                     PA-28-140            182
                      BEECH                     A36                  148
                                                                    ...
                      MCDONNELL DOUGLAS         MD-600                 1
                                                MD-83                  1
                                                MD-87                  1
                                                MD-88                  1
                      107.5 FLYING CORPORATION  ONE DESIGN DR 107      1
Length: 6094, dtype: int64

In this code, I used .loc with the condition df['Injury.Severity_copy'].isin(severity_values_to_find) to filter rows where 'Injury.Severity_copy' has values 'FATAL' or 'Unavailable'.

Then, I used ['Injury.Severity_copy', 'Make', 'Model'] inside .loc to access the 'Injury.Severity_copy', 'Make', and 'Model' columns for the filtered rows.

The variable corresponding_make_model is a DataFrame containing the 'Injury.Severity_copy', 'Make', and 'Model' values for rows where 'Injury.Severity_copy' has values 'FATAL' or 'Unavailable'.

When I printed corresponding_make_model, I included the value counts  to see the 'Injury.Severity_copy', 'Make', and 'Model' values side by side for the corresponding rows and their total counts.

There were 6,094 values returned so I'll filter that a bit more.

In [38]:
#I'll group by 'Make' and 'Model' and then count the occurances of "FATAL" or "Unavailable"
fatal_counts = fatality_correspond_make_model.groupby(['Make', 'Model']).size().nlargest(10)

print(fatal_counts)

Make      Model
CESSNA    152          250
          172          211
          172N         203
PIPER     PA-28-140    183
BEECH     A36          148
PIPER     PA-28-180    143
          PA-28-181    138
CESSNA    172M         133
ROBINSON  R44          117
BELL      206B         116
dtype: int64

In this code, I used groupby(['Make', 'Model']) to group the DataFrame based on the 'Make' and 'Model' columns, and then use size() to count the occurrences of each unique make/model pair with 'FATAL' or 'Unavailable' values.

Next, I used nlargest(10) to get the top 10 make/model pairs with the most frequent fatalities.

When I printed fatal_counts, it displayed the 10 make/model pairs with the most frequent fatalities along with their corresponding counts. These pairs represent the ones with the highest number of occurrences of 'FATAL' or 'Unavailable' in the 'Injury.Severity_copy' column.

In [42]:
#Now that I have a list of the worst planes to buy, I'll use the same strategy to 
#make a list of the best planes using fewest 'Incident'reports

#filter rows with 'Injury.Severity_copy' value 'Incident' and access corresponding 'Total.Uninjured', Make' and 'Model' columns
incident_correspond_make_model_uninjured = aviation_data_washed.loc[aviation_data_washed['Injury.Severity_copy'] == 'Incident', ['Total.Uninjured', 'Make', 'Model']]

#group by 'Make' and 'Model' and calculate the count occurances of 'Incident' and the maximum 'Total.Uninjured'
incident_uninjured_counts = incident_correspond_make_model_uninjured.groupby(['Make', 'Model']).agg({'Make':'first','Model':'first', 'Total.Uninjured':'max','Injury.Severity_copy':'size'})

#rename the columns for clarity
incident_uninjured_counts.columns = ['Make', 'Model', 'Max_Total_Uninjured', 'Incident_Count']

#Sort the DataFrame based on 'Incident_Count' in ascending order and 'Max_Total_Uninjured'in descending order
sorted_counts = incident_uninjured_counts.sort_values(by=['Incident_Count', 'Max_Total_Uninjured'], ascending=[True, False])

#get the top 10 make/model pairs with the least frequent 'Incidents' and the highest 'Total.Uninjured'
top_10_least_incidents_highest_uninjured = sorted_counts.head(10)


#view results
print(top_10_least_incidents_highest_uninjured)

SpecificationError: Column(s) ['Injury.Severity_copy'] do not exist

In [69]:
aviation_data_washed.info()

<class 'pandas.core.frame.DataFrame'>
Index: 88889 entries, 20001218X45444 to 20221230106513
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Investigation.Type      88889 non-null  object
 1   Accident.Number         88889 non-null  object
 2   Event.Date              88889 non-null  object
 3   Location                88837 non-null  object
 4   Country                 88663 non-null  object
 5   Latitude                34382 non-null  object
 6   Longitude               34373 non-null  object
 7   Airport.Code            50249 non-null  object
 8   Airport.Name            52790 non-null  object
 9   Injury.Severity         87889 non-null  object
 10  Aircraft.damage         85695 non-null  object
 11  Aircraft.Category       32287 non-null  object
 12  Registration.Number     87572 non-null  object
 13  Make                    88889 non-null  object
 14  Model                   88889 non-null  object
 15  Amateur.Built           88787 non-null  object
 16  Number.of.Engines       82805 non-null  float64
 17  Engine.Type             81812 non-null  object
 18  FAR.Description         32023 non-null  object
 19  Schedule                12582 non-null  object
 20  Purpose.of.flight       82697 non-null  object
 21  Air.carrier             16648 non-null  object
 22  Total.Fatal.Injuries    77488 non-null  float64
 23  Total.Serious.Injuries  76379 non-null  float64
 24  Total.Minor.Injuries    76956 non-null  float64
 25  Total.Uninjured         82977 non-null  float64
 26  Weather.Condition       84397 non-null  object
 27  Broad.phase.of.flight   61724 non-null  object
 28  Report.Status           82508 non-null  object
 29  Publication.Date        75118 non-null  object
 30  Injury.Severity_copy    88889 non-null  object
dtypes: float64(5), object(26)
memory usage: 21.7+ MB

Analyzing the aviation accident dataset can provide valuable insights that can lead to concrete business recommendations in various aspects of the aviation industry. Here are three potential business recommendations based on the analysis:

Safety Measures for High-Risk Aircraft Types: Analyze the accident data to identify aircraft types with higher accident rates and significant fatalities. Based on this analysis, the business can recommend implementing targeted safety measures and maintenance protocols for those high-risk aircraft types. This could include enhanced pilot training, more frequent inspections, improved maintenance procedures, and upgrades to critical components. By addressing safety concerns proactively, airlines and aircraft operators can reduce the risk of accidents and enhance passenger confidence, leading to better customer retention and improved safety records. (above)

Recommendations: 

1. Route Optimization and Incident Avoidance: Analyze accident data based on location and weather conditions to identify regions or flight paths that have historically experienced higher accident rates or incidents. Based on this analysis, airlines and aviation authorities can recommend optimizing flight routes to avoid high-risk areas. Additionally, real-time weather monitoring and predictive analytics can be used to identify potential hazardous conditions and recommend alternative routes or delayed departures to minimize risks. Implementing such measures can help reduce operational disruptions, save costs, and enhance passenger safety and satisfaction.


2. Improving Emergency Response and Crisis Management: Analyze accident data to identify common causes of accidents and incidents, such as mechanical failures, pilot error, or adverse weather. Based on this analysis, aviation companies and authorities can develop and enhance emergency response plans and crisis management protocols. Recommendations may include conducting regular emergency drills, ensuring effective communication channels between crew and ground staff, and coordinating with local authorities for efficient accident response. Implementing robust crisis management strategies can help minimize the impact of accidents, improve passenger trust, and protect the reputation of airlines and aviation operators.

3. What is the most dangerous phase of a flight: In a table, I will show the distinct phases ordered by the number of fatal accidents.

It's important to note that any business recommendations derived from data analysis should be accompanied by careful consideration of the specific context, regulatory requirements, and limitations of the dataset. Additionally, these recommendations should be subject to ongoing evaluation and refinement based on updated data and emerging industry practices.

Recommendation 1 process breakdown:

To perform the analysis of Route Optimization and Incident Avoidance I will follow these steps:

Data Preprocessing:

Load the aviation accident dataset using pandas DataFrame.
Handle missing values, if any.
Convert the latitude and longitude data into geometries using Geopandas and Shapely.
Prepare the data for analysis.

Data Analysis:

Analyze accident data based on location to identify regions with higher accident rates.
Analyze accident data based on weather conditions to understand their impact on accident rates.
Explore the correlation between specific weather conditions and accident severity.
Analyze historical accident trends over time.
Data Visualization with Matplotlib (or Tableau):

Use Matplotlib to create various plots and charts for visualizing accident data, weather conditions, and trends.
Export the cleaned and analyzed data to Tableau for interactive visualization and dashboard creation, if required by Flatiron.

In [ ]:
import geopandas as gpd
from shapely.geometry import Point
import matplotlib.pyplot as plt

# Convert latitude and longitude to geometries
geometry = [Point(xy) for xy in zip(df['Longitude'], df['Latitude'])]
gdf = gpd.GeoDataFrame(df, crs='EPSG:4326', geometry=geometry)

# Data Analysis
# Grouping accidents by latitude and longitude to identify regions with higher accident frequency
grouped_by_location = gdf.groupby(['Latitude', 'Longitude']).size().reset_index(name='Accident_Count')

# Grouping accidents based on weather conditions to analyze their impact on accident rates
grouped_by_weather = df.groupby(['Weather.Condition']).size().reset_index(name='Accident_Count')

# Explore the correlation between specific weather conditions and accident severity
weather_severity_corr = df.groupby(['Weather.Condition'])['Injury.Severity_copy'].value_counts(normalize=True).unstack()

# Analyzing historical accident trends over time
df['Event.Date'] = pd.to_datetime(df['Event.Date'])
accident_trends_over_time = df.groupby(df['Event.Date'].dt.year)['Event.Id'].count()

# Data Visualization with Matplotlib
# Create a bar plot for the accident count based on weather conditions
plt.figure(figsize=(10, 6))
plt.bar(grouped_by_weather['Weather.Condition'], grouped_by_weather['Accident_Count'])
plt.xlabel('Weather Conditions')
plt.ylabel('Accident Count')
plt.title('Accident Count based on Weather Conditions')
plt.xticks(rotation=45)
plt.show()

# Create a heatmap to visualize the correlation between weather conditions and accident severity
plt.figure(figsize=(10, 6))
plt.imshow(weather_severity_corr, cmap='coolwarm', interpolation='nearest')
plt.colorbar()
plt.xticks(range(len(weather_severity_corr.columns)), weather_severity_corr.columns, rotation=45)
plt.yticks(range(len(weather_severity_corr)), weather_severity_corr.index)
plt.title('Correlation between Weather Conditions and Accident Severity')
plt.show()

# Data Visualization with Tableau
# Export the cleaned and analyzed data to a CSV file for Tableau visualization
df.to_csv('aviation_data_washed_analyzed_1.csv', index=False)

#This code provides a data analysis using pandas and matplotlib. 
#It groups accident data based on location and weather conditions, 
#explores the correlation between weather conditions and accident 
#severity, and visualizes the accident count based on weather conditions 
#using a bar plot and a heatmap. For a more in-depth analysis and interactive 
#visualization, I could import the 'aviation_data_washed_analyzed_1.csv' 
#into Tableau and create customized dashboards with filters and interactive 
#elements to visualize the insights further.

Recommendation 2 process breakdown:

To perform the analysis of Improving Emergency Response and Crisis Management I will follow these steps:

Data Preprocessing:

Load the aviation accident dataset using pandas DataFrame.
Handle missing values, if any.
Prepare the data for analysis.

Data Analysis:

Analyze accident data to identify common causes of accidents and incidents.
Group accidents by factors such as mechanical failures, pilot error, and adverse weather conditions to understand their impact on accident rates.

Data Visualization with Matplotlib and Tableau:

Use Matplotlib to create various plots and charts for visualizing the distribution of accidents based on their causes.
Export the cleaned and analyzed data to Tableau for interactive visualization and dashboard creation.

In [ ]:
#import pandas as pd
#import matplotlib.pyplot as plt

# Load the aviation accident dataset

# Data Analysis
# Analyze accident data to identify common causes of accidents and incidents
common_causes = aviation_data_washed['Broad.phase.of.flight'].value_counts()

# Group accidents by factors such as mechanical failures, pilot error, and adverse weather conditions
mechanical_failures = aviation_data_washed[aviation_data_washed['Broad.phase.of.flight'] == 'MECHANICAL FAILURE']
pilot_error = aviation_data_washed[aviation_data_washed['Broad.phase.of.flight'] == 'PILOT ERROR']
adverse_weather = aviation_data_washed[aviation_data_washed['Weather.Condition'].isin(['RAIN', 'SNOW', 'FOG', 'THUNDERSTORM'])]

# Data Visualization with Matplotlib
# Create a bar plot to visualize the distribution of accidents based on their causes
plt.figure(figsize=(10, 6))
plt.bar(common_causes.index, common_causes.values)
plt.xlabel('Causes of Accidents')
plt.ylabel('Accident Count')
plt.title('Distribution of Accidents based on Common Causes')
plt.xticks(rotation=45)
plt.show()

# Data Visualization with Tableau
# Export the cleaned and analyzed data to a CSV file for Tableau visualization
df.to_csv('aviation_data_washed_analyzed_2.csv', index=False)

#The above code provides a basic data analysis using pandas and matplotlib. 
#It identifies common causes of accidents and incidents and groups accidents 
#based on factors such as mechanical failures, pilot error, and adverse 
#weather conditions. It also visualizes the distribution of accidents based 
#on their causes using a bar plot. For a more in-depth analysis and interactive 
#visualization, I could import the 'aviation_data_washed_analyzed_2.csv' 
#into Tableau and create customized dashboards with filters and interactive 
#elements to visualize the insights further.

Recommendation 3 process breakdown:
    
To analyze "Is it safer to take off or land?" I will follow these steps:

Data Preprocessing:

Load the aviation accident dataset using pandas DataFrame.
Handle missing values, if any.
Prepare the data for analysis.

Data Analysis:

Analyze the number of fatal accidents for each distinct phase of a flight.
Order the phases by the number of fatal accidents in descending order.

Data Visualization with Matplotlib and Tableau:

Create a table to display the distinct phases of a flight and their corresponding fatal accident counts.

In [ ]:
#import pandas as pd
#import matplotlib.pyplot as plt

# Load the aviation accident dataset

# Data Analysis
# Filter rows with fatal accidents
fatal_accidents_df = df[df['Injury.Severity_copy'] == 'FATAL']

# Analyze the number of fatal accidents for each distinct phase of a flight
fatal_phase_counts = fatal_accidents_df['Broad.phase.of.flight'].value_counts()

# Data Visualization with Matplotlib
# Create a table to display the distinct phases of a flight and their corresponding fatal accident counts
table_data = pd.DataFrame({'Flight Phase': fatal_phase_counts.index, 'Fatal Accidents Count': fatal_phase_counts.values})
table_data = table_data.sort_values(by='Fatal Accidents Count', ascending=False)

# Display the table
print(table_data)

# Data Visualization with Tableau
# Export the table_data to a CSV file for Tableau visualization
table_data.to_csv('fatal_phase_counts_table.csv', index=False)

EXTRA CODE BELOW

In [ ]:
#Using the same method as before to combine like values in the new column

#combine string and float data
aviation_data_washed['Injury.Severity_copy'] = aviation_data_washed['Injury.Severity_copy'].apply(str)

#now make them uppercase
aviation_data_washed['Injury.Severity_copy'] = aviation_data_washed['Injury.Severity_copy'].map(str.upper)

#how many missing values are there?
aviation_data_washed['Injury.Severity_copy'].value_counts()

In [ ]:
#scrap: How can I search for values of 'Incident' in the 'Injury.Severity_copy' column and then in the rows where 'Incident' is the value, look to see if there is a reported value of 1 or more in the 'Total.Fatal.Injuries' column?

In [ ]:
#first, I'll see if I can fill any missing values by inference based on the
#'Total.Fatal.Injuries' column.

#to infer these values I'm grouping the data based on 'Injury.Severity'
grouped_injuryseverity = aviation_data_washed.groupby('Injury.Severity')

#next, I'm calculating the average number of fatalities for each group
avg_fatalities_by_severity = grouped_injuryseverity['Total.Fatal.Injuries'].mean()

#lastly, I'm imputing any missing 'Total.Fatal.Injuries' values based on 'Injury.Severity'
for index, row in aviation_data_washed.iterrows():
    if pd.isnull(row['Total.Fatal.Injuries']):
        injury_severity =row['Injury.Severity']
        df.at[index, 'Total.Fatal.Injuries'] = avg_fatalities_by_severity[injury_severity]

#now, I'd like to see the updated DataFrame with the imputed missing values
print(aviation_data_washed)

In my approach above, I calculated the average number of fatalities for each severity group using the 'Injury.Severity' column. Then, I iteratively checked for missing 'Total.Fatal.Injuries' values, and for each missing value, I replaced it with the average value from the corresponding severity group.

This imputation method assumes that the severity of injuries ('Injury.Severity') is correlated with the number of fatalities ('Total.Fatal.Injuries'). The quality of the imputation will depend on the strength of this correlation. Always validate the imputation results and consider any potential biases introduced by this imputation strategy. Additionally, consider the size of the dataset and the distribution of values in the 'Injury.Severity' column to ensure meaningful imputations. If the dataset is limited or the correlation is weak, other imputation methods or more advanced modeling techniques might be more appropriate.- textbook definition

In [ ]:
#which 'makes' have the least amount of fatal crashes?
#normalize this by diving by the total number of incidents/accidents (investigation.type)frequency count? 

# determine fatal crashes
##predict: will fill all empty spots with zeros in total.fatal.injuries
#confirm: is there a way to check in total.fatal.injuries which rows have 
#missing data and what is written in another column for that row (injury.severity)?


#From NTSB definitions:

#An **accident** is defined as “an occurrence associated with the
#operation of an aircraft which takes place between the time any person
#boards the aircraft with the intention of flight and all such persons
#have disembarked, and in which any person suffers death or serious
#injury, or in which the aircraft receives substantial damage”. An
#**incident** is defined as “an occurrence other than an accident,
#associated with the operation of an aircraft, which affects or could
#affect the safety of operations.”

#Once I have most reliable make THEN view with the different models to see which model is safest
#not sure on the steps to do this

#for the 3 recommendations
#Where
    #Plot a map of all accidents. Since 2002, NTSB records of accidents 
    #and incidents occurring in the United States include `Latitude` and `Longitude` 
    #information. However, in some cases the latitude/longitude coordinates are estimated
    #from the nearest town or airport rather than the precise location of the
    #accident or incident site. Many observations have missing
    #latitude and longitude information, so obviously exclude them.

    #Plot a world map. Then, add information about the location,
    #aircraft damage and total number of fatal injuries of the accidents.
    
#When
    #Has the number of accidents decreased over time? 
    #Is flying safer today? 
    
    #group the accidents by date.
    
#Weather impact

    #Do the most of the fatal accidents occur in bad weather?
    
    #use the total.fatal.injuries and weather column? Not sure what operation to use here.